function countNT(seq::String)
    NTs, counts, output = Dict{Char,Int64}('A'=> 1,'C' => 2,'G' => 3,'T' => 4), [0,0,0,0], ""
    for nt in seq; counts[NTs[nt]] += 1 end
    for i in 1:4; output *= string(counts[i])*" " end
    return println(output)
end

countNT("CGAGTACAGAACTCGACTTCGTGATGTCAGGGAACAAGGTGTGCCGCTTGTTTACATTATCTATACCTAAGACCTGCACTCGTCAAGCGGATCCATTCTGAGAAAAGTCAGAGATCGTTGCGCGGATTCGGCGGTCTCTAAGCAAACCATTGACGCTGGCTTGGCGGATTGGCGACGTGGTAGCAAACATGAGGCTGGTTCTTCTTTGTTCGGTGAAGCTGAATTGTGATAAGGGACATTCATTAACCCGAACGTCAATCCTAGCTTCGCCAAGTATCATCTCGGAGCGCCCAAGCCGGCTTGCCTGCCACGACGAAGGTTTAGGACTTTTCGTATCCTACATCCTGATGCAGTAATGTTCACAACTAAAAGGAAGTTCACACATCTAAAAAGTAGAGCTAGTCTAAGGGTTGACGAGAGATGGATTATACGCGTGCATCTGTACGGCATGCACTCCCGCACCGAGCCACCCATCGTACACTGGTGCTTTACCCGCTGCGAAGCCGAAGATGTCTTTAAGAGTCCTGGCGGTGACGGGCCATGTCGTTAATTGAGGGTCCTACTTCGCTGACTACATAGATGCGGAGTACATTCTACTATGCAGACTGCTCCCGAGGCTTTGTCGGTACCATATTCTGAATGTATGCCTTCGCGTGATGATTCCAGCTGTCACGATCGGCTCCATACTTGTCGCCCAGGTGGCCCTCTCGTCCACGACACTACGGCAGGTCTTCTACAGCAGGACAACTTCCTTTCGTGGGTAAGAACATGTCATCTTAGGAACTAACTTAGAGAGACACAGTTCTGTTCCCTCGGTATAAGCAGGCGCGCTCTGATTAGGAGGATCAGTTGGAGCGCAAACGAGTTACAGCCGACACTATCCAGATCTTCCGCGATGAACGTGGCCTCAGCGATAAACAGACCTACAAGGCTGTTGC")
# 229 238 237 234 