function convert(dna::String)
    rna = ""
    for nt in dna
        if nt != 'T'
            rna *= nt
        else
            rna *= 'U'
        end
    end
    return println(rna)
end

convert("AGTATAACTGCCTGCGCAAACAAGAGTGAGGATACTTCGGGTACCCTTGATTCCACCTCGCCATTCCATCCCGCCGAACTAAGGGATACTGTTACAGCTTATATATGTCCGACTCAGGTTCGCAGCTAGAATCATTAGGCCAAGTCTTGCATTGATTCTGGATCTTACCCAAGCGCAGTGCGCTCCCGGGACCGATAATTCGCCGACCAACTGTCGTAATCTTCGTAAGGCGCCTTAAACTCACCGTAGGTTGGATACAACCTTGTTACCACGGTTTCACAGGGCGACACAACAGACATGGGGTCATAATGAACCTTCGCATTGCAATGGACCTGAGGATAAGGTATGAAATTCTATGGTTGAAACCAACTAAAATCCCAGTCCCGCCGTCGGAAATCTGCTTTGGCAAGGTGGGAACCCCCTATTTTTTAAAGCCGAGTTTTGTAGCTCCAGCCACGTTGACTCGATAAGCTCGATGGGGGCGGGACCTAGTGACCCCGTAAGGGAAAATAGCACCTCCAAACGAAAAACACGTGCCACGCAGGGGAGCTCAATACTTGACTAGACGCTTCTCACAGTGCACGAATTGAGTCACAAGCCACTAAAGCGCTTCTTTGAATCACTTCTATCCTGGCCATATATGTGTCTTCATGAATATTCGAGAGGGCAATTCATTTATGTCTATCCTCAGTGGCGGGAGATTGTGCTCCTTCTGGCCTGCACCCTTAATGTCTATAGAGTGACTAGGCGTTGGTCTAGCAACGTGTTATATACCTTTGTGTAAATTTCGTGTATTACACCCAAGCCGGATTTCTCTTTTAGAGGTGGCGCCCCACCGTTATCCTCCCCCTTTAGATGAGACGGTTGCGTCGGGTGTAGCGAGCGGCGCGAAGTTACCCCCTTAGACTTGCCCAAGTTTCACTCCTTGCTTCGAGATGCCGCAAACGCCTTCCAG
")

